#!/usr/bin/python

import BlastoiseFirstTurn as bft
import unittest
from copy import deepcopy
from PlayerState import PlayerState
import CardTypes as c
import CardFactory as cf

import ArchiesAceintheHole
import BattleCompressor
import Bicycle
import Blastoise
import ComputerTrainer
import DowsingMachine
import EscapeRope
import Exeggcute
import GrassEnergy
import JirachiEX
import KeldeoEX
import LysandersTrumpCard
import Maintenance
import N
import PrimalKyogreEX
import ProfessorJuniper
import RandomReceiver
import Skyla
import Suicune
import SuperiorEnergyRetriever
import UltraBall
import VSSeeker
import WaterEnergy


def checkHand(test, p, expr):
    memoization = dict()
    test.assertEqual(bft.BlastoiseFirstTurn(deepcopy(p), 
                                            memoization), expr)

class TestBlastoiseFirstTurn(unittest.TestCase):
    def test_EmptyHand(self):
        checkHand(self, PlayerState(), False)

    def test_SimpleSingleVSSeeker(self):
        checkHand(self, PlayerState(hand=[VSSeeker.VSSeeker()]), False)

    def test_SimpleSingleVSSeekerAndBlastoise(self):
        p = PlayerState(hand=[VSSeeker.VSSeeker()],
                        discard=[Blastoise.Blastoise()])
        checkHand(self, p, False)

    def test_SimpleSingleVSSeekerArchieAndBlastoise(self):
        p = PlayerState()
        p.hand.append(cf.create("Archie's Ace in the Hole"))
        p.hand.append(cf.create("VS Seeker"))
        p.discard.append(cf.create("Blastoise"))
        checkHand(self, p, False)

    def test_SimpleBlastoiseFirstTurn(self):
        p = PlayerState()
        p.hand.append(cf.create("Archie's Ace in the Hole"))
        p.discard.append(cf.create("Blastoise"))
        p.deck.append(cf.create("Water Energy"))
        p.deck.append(cf.create("Water Energy"))
        p.deck.append(cf.create("Water Energy"))
        p.deck.append(cf.create("Water Energy"))
        p.deck.append(cf.create("Water Energy"))
        checkHand(self, p, True)

    def test_SimpleBlastoiseFirstTurnVsSeeker(self):
        p = PlayerState()
        p.hand.append(cf.create("VS Seeker"))
        p.discard.append(cf.create("Archie's Ace in the Hole"))
        p.discard.append(cf.create("Blastoise"))
        p.deck.append(cf.create("Water Energy"))
        p.deck.append(cf.create("Water Energy"))
        p.deck.append(cf.create("Water Energy"))
        p.deck.append(cf.create("Water Energy"))
        p.deck.append(cf.create("Water Energy"))
        checkHand(self, p, True)

    def test_EmptyDiscard(self):
        p = PlayerState()
        p.hand.append(cf.create("Archie's Ace in the Hole"))
        checkHand(self, p, False)

    def test_NotEnoughCards(self):
        p = PlayerState()
        p.hand.append(cf.create("Archie's Ace in the Hole"))
        p.hand.append(cf.create("Ultra Ball"))
        p.discard.append(cf.create("Blastoise"))
        checkHand(self, p, False)

    def test_ExtraSupporter(self):
        p = PlayerState()
        p.hand.append(cf.create("Archie's Ace in the Hole"))
        p.hand.append(cf.create("Archie's Ace in the Hole"))
        p.discard.append(cf.create("Blastoise"))
        checkHand(self, p, False)

    def test_BlastoiseFirstTurnWithExtraItem(self):
        p = PlayerState()
        p.hand.append(cf.create("Archie's Ace in the Hole"))
        p.hand.append(cf.create("Battle Compressor"))
        p.hand.append(cf.create("Battle Compressor"))
        p.hand.append(cf.create("Battle Compressor"))
        p.deck.append(cf.create("Water Energy"))
        p.deck.append(cf.create("Water Energy"))
        p.deck.append(cf.create("Water Energy"))
        p.deck.append(cf.create("Water Energy"))
        p.deck.append(cf.create("Water Energy"))
        p.deck.append(cf.create("Water Energy"))
        p.deck.append(cf.create("Water Energy"))
        p.deck.append(cf.create("Water Energy"))
        p.deck.append(cf.create("Water Energy"))
        p.deck.append(cf.create("Water Energy"))
        p.deck.append(cf.create("Water Energy"))
        p.deck.append(cf.create("Water Energy"))
        p.deck.append(cf.create("Water Energy"))
        p.deck.append(cf.create("Water Energy"))
        p.discard.append(cf.create("Blastoise"))
        checkHand(self, p, True)

    def test_ExtraItemAndExtraSupporter(self):
        p = PlayerState()
        p.hand.append(cf.create("Archie's Ace in the Hole"))
        p.hand.append(cf.create("Archie's Ace in the Hole"))
        p.hand.append(cf.create("Battle Compressor"))
        p.hand.append(cf.create("Battle Compressor"))
        p.hand.append(cf.create("Battle Compressor"))
        p.discard.append(cf.create("Blastoise"))
        checkHand(self, p, False)

    def test_Discard(self):
        p = PlayerState()
        p.hand.append(cf.create("Archie's Ace in the Hole"))
        p.hand.append(cf.create("Blastoise"))
        p.hand.append(cf.create("Blastoise"))
        p.hand.append(cf.create("Ultra Ball"))
        p.deck.append(cf.create("Ultra Ball"))
        p.deck.append(cf.create("Ultra Ball"))
        p.deck.append(cf.create("Ultra Ball"))
        p.deck.append(cf.create("Ultra Ball"))
        p.deck.append(cf.create("Ultra Ball"))
        p.deck.append(cf.create("Ultra Ball"))
        checkHand(self, p, True)

    def test_DiscardAndVSSeeker(self):
        p = PlayerState()
        p.hand.append(cf.create("Archie's Ace in the Hole"))
        p.hand.append(cf.create("Blastoise"))
        p.hand.append(cf.create("VS Seeker"))
        p.hand.append(cf.create("Ultra Ball"))
        p.deck.append(cf.create("Ultra Ball"))
        p.deck.append(cf.create("Ultra Ball"))
        p.deck.append(cf.create("Ultra Ball"))
        p.deck.append(cf.create("Ultra Ball"))
        p.deck.append(cf.create("Ultra Ball"))
        checkHand(self, p, True)

    def test_MultiDiscard(self):
        p = PlayerState()
        p.hand.append(cf.create("Archie's Ace in the Hole"))
        p.hand.append(cf.create("Battle Compressor"))
        p.hand.append(cf.create("Battle Compressor"))
        p.hand.append(cf.create("Blastoise"))
        p.hand.append(cf.create("Blastoise"))
        p.hand.append(cf.create("Ultra Ball"))
        p.hand.append(cf.create("Ultra Ball"))
        p.deck.append(cf.create("Ultra Ball"))
        p.deck.append(cf.create("Ultra Ball"))
        p.deck.append(cf.create("Ultra Ball"))
        p.deck.append(cf.create("Ultra Ball"))
        p.deck.append(cf.create("Ultra Ball"))
        p.deck.append(cf.create("Ultra Ball"))
        checkHand(self, p, True)

    def test_MultiDiscardExtraItem(self):
        p = PlayerState()
        p.hand.append(cf.create("Archie's Ace in the Hole"))
        p.hand.append(cf.create("Battle Compressor"))
        p.hand.append(cf.create("Battle Compressor"))
        p.hand.append(cf.create("Battle Compressor"))
        p.hand.append(cf.create("Blastoise"))
        p.hand.append(cf.create("Blastoise"))
        p.hand.append(cf.create("Ultra Ball"))
        p.hand.append(cf.create("Ultra Ball"))
        p.deck.append(cf.create("Ultra Ball"))
        p.deck.append(cf.create("Ultra Ball"))
        p.deck.append(cf.create("Ultra Ball"))
        p.deck.append(cf.create("Ultra Ball"))
        p.deck.append(cf.create("Ultra Ball"))
        p.deck.append(cf.create("Ultra Ball"))
        checkHand(self, p, True)

    def test_MultiDiscardManySupporters(self):
        p = PlayerState()
        p.hand.append(cf.create("Archie's Ace in the Hole"))
        p.hand.append(cf.create("Archie's Ace in the Hole"))
        p.hand.append(cf.create("Archie's Ace in the Hole"))
        p.hand.append(cf.create("Archie's Ace in the Hole"))
        p.hand.append(cf.create("Blastoise"))
        p.hand.append(cf.create("Blastoise"))
        p.hand.append(cf.create("Ultra Ball"))
        p.hand.append(cf.create("Ultra Ball"))
        checkHand(self, p, False)

    def test_Energy(self):
        p = PlayerState()
        p.hand.append(cf.create("Water Energy"))
        p.hand.append(cf.create("Archie's Ace in the Hole"))
        p.discard.append(cf.create("Blastoise"))
        p.bench.append(cf.create("Keldeo EX"))
        p.deck.append(cf.create("Keldeo EX"))
        p.deck.append(cf.create("Keldeo EX"))
        p.deck.append(cf.create("Keldeo EX"))
        p.deck.append(cf.create("Keldeo EX"))
        p.deck.append(cf.create("Keldeo EX"))
        checkHand(self, p, True)

    def test_TooMuchEnergy(self):
        p = PlayerState()
        p.hand.append(cf.create("Archie's Ace in the Hole"))
        p.hand.append(cf.create("Water Energy"))
        p.hand.append(cf.create("Water Energy"))
        p.discard.append(cf.create("Blastoise"))
        checkHand(self, p, False)

    def test_DiscardEnergy(self):
        p = PlayerState()
        p.hand.append(cf.create("Archie's Ace in the Hole"))
        p.hand.append(cf.create("Water Energy"))
        p.hand.append(cf.create("Water Energy"))
        p.hand.append(cf.create("Ultra Ball"))
        p.deck.append(cf.create("N"))
        p.deck.append(cf.create("N"))
        p.deck.append(cf.create("N"))
        p.deck.append(cf.create("N"))
        p.deck.append(cf.create("N"))
        p.deck.append(cf.create("N"))
        p.discard.append(cf.create("Blastoise"))
        checkHand(self, p, True)

    def test_DiscardEnergyAndBlastoise(self):
        p = PlayerState()
        p.hand.append(cf.create("Archie's Ace in the Hole"))
        p.hand.append(cf.create("Water Energy"))
        p.hand.append(cf.create("Water Energy"))
        p.hand.append(cf.create("Ultra Ball"))
        p.hand.append(cf.create("Blastoise"))
        p.deck.append(cf.create("Blastoise"))
        p.deck.append(cf.create("Blastoise"))
        p.deck.append(cf.create("Blastoise"))
        p.deck.append(cf.create("Blastoise"))
        p.deck.append(cf.create("Blastoise"))
        p.deck.append(cf.create("Blastoise"))
        checkHand(self, p, True)

    def test_Basic(self):
        p = PlayerState()
        p.hand.append(cf.create("Archie's Ace in the Hole"))
        p.hand.append(cf.create("Keldeo EX"))
        p.discard.append(cf.create("Blastoise"))
        p.deck.append(cf.create("Water Energy"))
        p.deck.append(cf.create("Water Energy"))
        p.deck.append(cf.create("Water Energy"))
        p.deck.append(cf.create("Water Energy"))
        p.deck.append(cf.create("Water Energy"))
        checkHand(self, p, True)

    def test_MultipleBasics(self):
        p = PlayerState()
        p.hand.append(cf.create("Archie's Ace in the Hole"))
        p.hand.append(cf.create("Keldeo EX"))
        p.hand.append(cf.create("Keldeo EX"))
        p.hand.append(cf.create("Keldeo EX"))
        p.hand.append(cf.create("Keldeo EX"))
        p.hand.append(cf.create("Keldeo EX"))
        p.deck.append(cf.create("Keldeo EX"))
        p.deck.append(cf.create("Keldeo EX"))
        p.deck.append(cf.create("Keldeo EX"))
        p.deck.append(cf.create("Keldeo EX"))
        p.deck.append(cf.create("Keldeo EX"))
        p.deck.append(cf.create("Keldeo EX"))
        p.discard.append(cf.create("Blastoise"))
        checkHand(self, p, False)

    def test_FullBench(self):
        p = PlayerState()
        p.hand.append(cf.create("Archie's Ace in the Hole"))
        p.hand.append(cf.create("Keldeo EX"))
        p.bench.append(cf.create("Keldeo EX"))
        p.bench.append(cf.create("Keldeo EX"))
        p.bench.append(cf.create("Keldeo EX"))
        p.bench.append(cf.create("Keldeo EX"))
        p.bench.append(cf.create("Keldeo EX"))
        p.discard.append(cf.create("Blastoise"))
        checkHand(self, p, False)

    def test_TooManyBasics(self):
        p = PlayerState()
        p.hand.append(cf.create("Archie's Ace in the Hole"))
        p.hand.append(cf.create("Keldeo EX"))
        p.hand.append(cf.create("Keldeo EX"))
        p.hand.append(cf.create("Keldeo EX"))
        p.hand.append(cf.create("Keldeo EX"))
        p.hand.append(cf.create("Keldeo EX"))
        p.hand.append(cf.create("Keldeo EX"))
        p.discard.append(cf.create("Blastoise"))
        checkHand(self, p, False)

    def test_Exeggcute(self):
        p = PlayerState()
        p.hand.append(cf.create("Archie's Ace in the Hole"))
        p.hand.append(cf.create("Blastoise"))
        p.hand.append(cf.create("Ultra Ball"))
        p.discard.append(cf.create("Exeggcute"))
        p.deck.append(cf.create("Exeggcute"))
        p.deck.append(cf.create("Exeggcute"))
        p.deck.append(cf.create("Exeggcute"))
        p.deck.append(cf.create("Exeggcute"))
        p.deck.append(cf.create("Exeggcute"))
        p.deck.append(cf.create("Exeggcute"))
        checkHand(self, p, True)

    def test_BlastoiseBattleCompressor(self):
        p = PlayerState()
        p.hand.append(cf.create("Battle Compressor"))
        p.hand.append(cf.create("Archie's Ace in the Hole"))
        p.deck.append(cf.create("Blastoise"))
        p.deck.append(cf.create("Blastoise"))
        p.deck.append(cf.create("Blastoise"))
        p.deck.append(cf.create("Blastoise"))
        p.deck.append(cf.create("Blastoise"))
        p.deck.append(cf.create("Blastoise"))
        checkHand(self, p, True)

    def test_ArchieVSSeekerBattleCompressor(self):
        p = PlayerState()
        p.hand.append(cf.create("Battle Compressor"))
        p.hand.append(cf.create("VS Seeker"))
        p.deck.append(cf.create("Archie's Ace in the Hole"))
        p.deck.append(cf.create("Archie's Ace in the Hole"))
        p.deck.append(cf.create("Archie's Ace in the Hole"))
        p.deck.append(cf.create("Archie's Ace in the Hole"))
        p.deck.append(cf.create("Archie's Ace in the Hole"))
        p.deck.append(cf.create("Archie's Ace in the Hole"))
        p.deck.append(cf.create("Archie's Ace in the Hole"))
        p.discard.append(cf.create("Blastoise"))
        checkHand(self, p, True)

    def test_ArchieAndBlastoiseVSSeekerBattleCompressor(self):
        p = PlayerState()
        p.hand.append(cf.create("Battle Compressor"))
        p.hand.append(cf.create("VS Seeker"))
        p.deck.append(cf.create("Archie's Ace in the Hole"))
        p.deck.append(cf.create("Blastoise"))
        p.deck.append(cf.create("Blastoise"))
        p.deck.append(cf.create("Blastoise"))
        p.deck.append(cf.create("Blastoise"))
        p.deck.append(cf.create("Blastoise"))
        p.deck.append(cf.create("Blastoise"))
        p.deck.append(cf.create("Blastoise"))
        checkHand(self, p, True)

    def test_ArchieAndBlastoiseNoVSSeekerBattleCompressor(self):
        p = PlayerState()
        p.hand.append(cf.create("Battle Compressor"))
        p.deck.append(cf.create("Archie's Ace in the Hole"))
        p.deck.append(cf.create("Blastoise"))
        p.deck.append(cf.create("Blastoise"))
        p.deck.append(cf.create("Blastoise"))
        p.deck.append(cf.create("Blastoise"))
        p.deck.append(cf.create("Blastoise"))
        p.deck.append(cf.create("Blastoise"))
        checkHand(self, p, False)

    def test_UltraBallToGetBlastoise(self):
        p = PlayerState()
        p.hand.append(cf.create("Archie's Ace in the Hole"))
        p.hand.append(cf.create("Archie's Ace in the Hole"))
        p.hand.append(cf.create("Archie's Ace in the Hole"))
        p.hand.append(cf.create("Archie's Ace in the Hole"))
        p.hand.append(cf.create("Ultra Ball"))
        p.hand.append(cf.create("Ultra Ball"))
        p.deck.append(cf.create("Blastoise"))
        p.deck.append(cf.create("Blastoise"))
        p.deck.append(cf.create("Blastoise"))
        p.deck.append(cf.create("Blastoise"))
        p.deck.append(cf.create("Blastoise"))
        p.deck.append(cf.create("Blastoise"))
        p.deck.append(cf.create("VS Seeker"))
        checkHand(self, p, True)

    def test_UltraBallToGetKeldeoEX_1(self):
        p = PlayerState()
        p.hand.append(cf.create("Archie's Ace in the Hole"))
        p.hand.append(cf.create("Archie's Ace in the Hole"))
        p.hand.append(cf.create("Ultra Ball"))
        p.hand.append(cf.create("Ultra Ball"))
        p.deck.append(cf.create("Keldeo EX"))
        p.deck.append(cf.create("Keldeo EX"))
        p.deck.append(cf.create("Keldeo EX"))
        p.deck.append(cf.create("Keldeo EX"))
        p.deck.append(cf.create("Keldeo EX"))
        p.deck.append(cf.create("Keldeo EX"))
        p.discard.append(cf.create("Blastoise"))
        checkHand(self, p, True)

    def test_UltraBallToGetKeldeoEX_2(self):
        p = PlayerState()
        p.hand.append(cf.create("Archie's Ace in the Hole"))
        p.hand.append(cf.create("Archie's Ace in the Hole"))
        p.hand.append(cf.create("Archie's Ace in the Hole"))
        p.hand.append(cf.create("Ultra Ball"))
        p.deck.append(cf.create("Keldeo EX"))
        p.deck.append(cf.create("Keldeo EX"))
        p.deck.append(cf.create("Keldeo EX"))
        p.deck.append(cf.create("Keldeo EX"))
        p.deck.append(cf.create("Keldeo EX"))
        p.deck.append(cf.create("Keldeo EX"))
        p.discard.append(cf.create("Blastoise"))
        checkHand(self, p, True)

    def test_UltraBallToGetKeldeoEX_3(self):
        p = PlayerState()
        p.hand.append(cf.create("Archie's Ace in the Hole"))
        p.hand.append(cf.create("Archie's Ace in the Hole"))
        p.hand.append(cf.create("Archie's Ace in the Hole"))
        p.hand.append(cf.create("Ultra Ball"))
        p.deck.append(cf.create("Keldeo EX"))
        p.deck.append(cf.create("Keldeo EX"))
        p.deck.append(cf.create("Keldeo EX"))
        p.deck.append(cf.create("Keldeo EX"))
        p.deck.append(cf.create("Keldeo EX"))
        p.deck.append(cf.create("Keldeo EX"))
        p.deck.append(cf.create("Keldeo EX"))
        p.bench.append(cf.create("Keldeo EX"))
        p.discard.append(cf.create("Blastoise"))
        checkHand(self, p, True)

    def test_UltraBallToGetKeldeoEX_3(self):
        p = PlayerState()
        p.hand.append(cf.create("Archie's Ace in the Hole"))
        p.hand.append(cf.create("Archie's Ace in the Hole"))
        p.hand.append(cf.create("Archie's Ace in the Hole"))
        p.hand.append(cf.create("Ultra Ball"))
        p.deck.append(cf.create("Keldeo EX"))
        p.deck.append(cf.create("Keldeo EX"))
        p.deck.append(cf.create("Keldeo EX"))
        p.deck.append(cf.create("Keldeo EX"))
        p.deck.append(cf.create("Keldeo EX"))
        p.deck.append(cf.create("Keldeo EX"))
        p.deck.append(cf.create("Keldeo EX"))
        p.bench.append(cf.create("Keldeo EX"))
        p.bench.append(cf.create("Keldeo EX"))
        p.bench.append(cf.create("Keldeo EX"))
        p.bench.append(cf.create("Keldeo EX"))
        p.bench.append(cf.create("Keldeo EX"))
        p.discard.append(cf.create("Blastoise"))
        checkHand(self, p, False)

    def test_UltraBallToGetNothing(self):
        p = PlayerState()
        p.hand.append(cf.create("Archie's Ace in the Hole"))
        p.hand.append(cf.create("Archie's Ace in the Hole"))
        p.hand.append(cf.create("Archie's Ace in the Hole"))
        p.hand.append(cf.create("Ultra Ball"))
        p.discard.append(cf.create("Blastoise"))
        p.deck.append(cf.create("VS Seeker"))
        p.deck.append(cf.create("VS Seeker"))
        p.deck.append(cf.create("VS Seeker"))
        p.deck.append(cf.create("VS Seeker"))
        p.deck.append(cf.create("VS Seeker"))
        checkHand(self, p, True)

    def test_UltraBallToGetExeggcute(self):
        p = PlayerState()
        p.hand.append(cf.create("Archie's Ace in the Hole"))
        p.hand.append(cf.create("Archie's Ace in the Hole"))
        p.hand.append(cf.create("Archie's Ace in the Hole"))
        p.hand.append(cf.create("Archie's Ace in the Hole"))
        p.hand.append(cf.create("Ultra Ball"))
        p.hand.append(cf.create("Ultra Ball"))
        p.discard.append(cf.create("Blastoise"))
        p.deck.append(cf.create("Exeggcute"))
        p.deck.append(cf.create("Ultra Ball"))
        p.deck.append(cf.create("Ultra Ball"))
        p.deck.append(cf.create("Ultra Ball"))
        p.deck.append(cf.create("Ultra Ball"))
        p.deck.append(cf.create("Ultra Ball"))
        checkHand(self, p, True)

    def test_ComputerTrainerToGetArchie(self):
        p = PlayerState()
        p.hand.append(cf.create("Computer Trainer"))
        p.hand.append(cf.create("Water Energy"))
        p.hand.append(cf.create("Water Energy"))
        p.deck.append(cf.create("Archie's Ace in the Hole"))
        p.deck.append(cf.create("Archie's Ace in the Hole"))
        p.deck.append(cf.create("Archie's Ace in the Hole"))
        p.deck.append(cf.create("Archie's Ace in the Hole"))
        p.deck.append(cf.create("Archie's Ace in the Hole"))
        p.deck.append(cf.create("Archie's Ace in the Hole"))
        p.discard.append(cf.create("Blastoise"))
        checkHand(self, p, True)

    def test_ComputerTrainerToGetVSSeeker(self):
        p = PlayerState()
        p.hand.append(cf.create("Computer Trainer"))
        p.hand.append(cf.create("Water Energy"))
        p.hand.append(cf.create("Water Energy"))
        p.deck.append(cf.create("VS Seeker"))
        p.deck.append(cf.create("VS Seeker"))
        p.deck.append(cf.create("VS Seeker"))
        p.deck.append(cf.create("VS Seeker"))
        p.deck.append(cf.create("VS Seeker"))
        p.deck.append(cf.create("VS Seeker"))
        p.discard.append(cf.create("Archie's Ace in the Hole"))
        p.discard.append(cf.create("Blastoise"))
        checkHand(self, p, True)

    def test_ComputerTrainerToGetBattleCompressor(self):
        p = PlayerState()
        p.hand.append(cf.create("Computer Trainer"))
        p.hand.append(cf.create("Water Energy"))
        p.hand.append(cf.create("Water Energy"))
        p.hand.append(cf.create("VS Seeker"))
        p.deck.append(cf.create("Archie's Ace in the Hole"))
        p.deck.append(cf.create("Archie's Ace in the Hole"))
        p.deck.append(cf.create("Archie's Ace in the Hole"))
        p.deck.append(cf.create("Archie's Ace in the Hole"))
        p.deck.append(cf.create("Archie's Ace in the Hole"))
        p.deck.append(cf.create("Archie's Ace in the Hole"))
        p.deck.append(cf.create("Archie's Ace in the Hole"))
        p.deck.append(cf.create("Archie's Ace in the Hole"))
        p.deck.append(cf.create("Battle Compressor"))
        p.deck.append(cf.create("Blastoise"))
        checkHand(self, p, True)

    def test_ComputerTrainerToGetWaterEnergy(self):
        p = PlayerState()
        p.hand.append(cf.create("Archie's Ace in the Hole"))
        p.hand.append(cf.create("Computer Trainer"))
        p.hand.append(cf.create("Water Energy"))
        p.hand.append(cf.create("Water Energy"))
        p.deck.append(cf.create("Water Energy"))
        p.deck.append(cf.create("Water Energy"))
        p.deck.append(cf.create("Water Energy"))
        p.deck.append(cf.create("Water Energy"))
        p.deck.append(cf.create("Water Energy"))
        p.deck.append(cf.create("Water Energy"))
        p.discard.append(cf.create("Blastoise"))
        checkHand(self, p, True)

    def test_ComputerTrainerToGetBlastoise(self):
        p = PlayerState()
        p.hand.append(cf.create("Archie's Ace in the Hole"))
        p.hand.append(cf.create("Archie's Ace in the Hole"))
        p.hand.append(cf.create("Archie's Ace in the Hole"))
        p.hand.append(cf.create("Archie's Ace in the Hole"))
        p.hand.append(cf.create("Computer Trainer"))
        p.hand.append(cf.create("Ultra Ball"))
        p.deck.append(cf.create("Blastoise"))
        p.deck.append(cf.create("Blastoise"))
        p.deck.append(cf.create("Blastoise"))
        p.deck.append(cf.create("Blastoise"))
        p.deck.append(cf.create("Blastoise"))
        p.deck.append(cf.create("Blastoise"))
        p.deck.append(cf.create("Blastoise"))
        checkHand(self, p, True)

    def test_LongBlastoiseFirstTurn(self):
        p = PlayerState()
        p.deck.append(cf.create("Professor Juniper"))
        p.deck.append(cf.create("Battle Compressor"))
        p.deck.append(cf.create("Blastoise"))
        p.deck.append(cf.create("Water Energy"))
        p.deck.append(cf.create("VS Seeker"))
        p.deck.append(cf.create("VS Seeker"))
        p.deck.append(cf.create("Water Energy"))
        p.deck.append(cf.create("VS Seeker"))
        p.deck.append(cf.create("Water Energy"))
        p.deck.append(cf.create("Maintenance"))
        p.deck.append(cf.create("Keldeo EX"))
        p.deck.append(cf.create("Water Energy"))
        p.deck.append(cf.create("Superior Energy Retriever"))
        p.deck.append(cf.create("Superior Energy Retriever"))
        p.deck.append(cf.create("Superior Energy Retriever"))
        p.deck.append(cf.create("N"))
        p.deck.append(cf.create("Blastoise"))
        p.deck.append(cf.create("Water Energy"))
        p.deck.append(cf.create("Professor Juniper"))
        p.deck.append(cf.create("Water Energy"))
        p.deck.append(cf.create("Water Energy"))
        p.deck.append(cf.create("Maintenance"))
        p.deck.append(cf.create("Keldeo EX"))
        p.deck.append(cf.create("Skyla"))
        p.deck.append(cf.create("Maintenance"))
        p.deck.append(cf.create("Ultra Ball"))
        p.deck.append(cf.create("Archie's Ace in the Hole"))
        p.deck.append(cf.create("Water Energy"))
        p.deck.append(cf.create("Battle Compressor"))
        p.deck.append(cf.create("Keldeo EX"))
        p.deck.append(cf.create("Ultra Ball"))
        p.deck.append(cf.create("VS Seeker"))
        p.deck.append(cf.create("Maintenance"))
        p.deck.append(cf.create("Battle Compressor"))
        p.deck.append(cf.create("Professor Juniper"))
        p.deck.append(cf.create("Skyla"))
        p.deck.append(cf.create("Professor Juniper"))
        p.deck.append(cf.create("Escape Rope"))
        p.deck.append(cf.create("Water Energy"))
        p.deck.append(cf.create("Superior Energy Retriever"))
        p.deck.append(cf.create("Water Energy"))
        p.deck.append(cf.create("Archie's Ace in the Hole"))
        p.deck.append(cf.create("Water Energy"))
        p.deck.append(cf.create("Ultra Ball"))
        p.deck.append(cf.create("Bicycle"))
        p.deck.append(cf.create("Suicune"))
        p.prizes.append(cf.create("Battle Compressor"))
        p.prizes.append(cf.create("Bicycle"))
        p.prizes.append(cf.create("Water Energy"))
        p.prizes.append(cf.create("Skyla"))
        p.prizes.append(cf.create("Skyla"))
        p.prizes.append(cf.create("Exeggcute"))
        p.bench.append(cf.create("Suicune"))
        p.hand.append(cf.create("Computer Trainer"))
        p.hand.append(cf.create("Water Energy"))
        p.hand.append(cf.create("N"))
        p.hand.append(cf.create("Water Energy"))
        p.hand.append(cf.create("Water Energy"))
        p.hand.append(cf.create("Ultra Ball"))
        p.hand.append(cf.create("Water Energy"))
        checkHand(self, p, False)

    def test_LongBlastoiseFirstTurn2(self):
        p = PlayerState()
        p.hand.append(cf.create("Battle Compressor"))
        p.hand.append(cf.create("Water Energy"))
        p.hand.append(cf.create("Escape Rope"))
        p.hand.append(cf.create("Skyla"))
        p.hand.append(cf.create("Computer Trainer"))
        p.hand.append(cf.create("Water Energy"))
        p.hand.append(cf.create("Professor Juniper"))
        p.deck.append(cf.create("N"))
        p.deck.append(cf.create("Water Energy"))
        p.deck.append(cf.create("VS Seeker"))
        p.deck.append(cf.create("Ultra Ball"))
        p.deck.append(cf.create("Water Energy"))
        p.deck.append(cf.create("Ultra Ball"))
        p.deck.append(cf.create("Blastoise"))
        p.deck.append(cf.create("Maintenance"))
        p.deck.append(cf.create("Blastoise"))
        p.deck.append(cf.create("Water Energy"))
        p.deck.append(cf.create("Water Energy"))
        p.deck.append(cf.create("Skyla"))
        p.deck.append(cf.create("Keldeo EX"))
        p.deck.append(cf.create("Battle Compressor"))
        p.deck.append(cf.create("Battle Compressor"))
        p.deck.append(cf.create("Maintenance"))
        p.deck.append(cf.create("Ultra Ball"))
        p.deck.append(cf.create("Maintenance"))
        p.deck.append(cf.create("Battle Compressor"))
        p.deck.append(cf.create("Water Energy"))
        p.deck.append(cf.create("Professor Juniper"))
        p.deck.append(cf.create("Keldeo EX"))
        p.deck.append(cf.create("Superior Energy Retriever"))
        p.deck.append(cf.create("Water Energy"))
        p.deck.append(cf.create("N"))
        p.deck.append(cf.create("Water Energy"))
        p.deck.append(cf.create("Professor Juniper"))
        p.deck.append(cf.create("Water Energy"))
        p.deck.append(cf.create("Archie's Ace in the Hole"))
        p.deck.append(cf.create("Professor Juniper"))
        p.deck.append(cf.create("Water Energy"))
        p.deck.append(cf.create("Superior Energy Retriever"))
        p.deck.append(cf.create("Ultra Ball"))
        p.deck.append(cf.create("Water Energy"))
        p.deck.append(cf.create("Water Energy"))
        p.deck.append(cf.create("VS Seeker"))
        p.deck.append(cf.create("Water Energy"))
        p.deck.append(cf.create("Keldeo EX"))
        p.deck.append(cf.create("Water Energy"))
        p.deck.append(cf.create("Suicune"))
        p.deck.append(cf.create("Bicycle"))
        p.deck.append(cf.create("Exeggcute"))
        p.deck.append(cf.create("Skyla"))
        p.deck.append(cf.create("Water Energy"))
        p.deck.append(cf.create("Skyla"))
        p.deck.append(cf.create("VS Seeker"))
        p.prizes.append(cf.create("Superior Energy Retriever"))
        p.prizes.append(cf.create("Maintenance"))
        p.prizes.append(cf.create("Superior Energy Retriever"))
        p.prizes.append(cf.create("VS Seeker"))
        p.prizes.append(cf.create("Archie's Ace in the Hole"))
        p.prizes.append(cf.create("Bicycle"))
        p.bench.append(cf.create("Suicune"))
        checkHand(self, p, False)

if __name__ == '__main__':
    unittest.main()

